---
title: "midori7"
author: "Toshihide Imaruoka"
date: "12/21/2022"
output:
  rmdformats::downcute:
    highlight: kate
    css: mycss.css
    dev: "ragg_png"
---
# 7. 一般化線形混合モデル（GLMM）--個体差のモデリング--
  * GLM: 応答変数$y_i$を説明変数$x_i$と結びつける
    * そのための部品が確率分布、リンク関数、線形予測子
    * データに合うモデルを作る方法なんだけど、現実のデータに含まれるばらつきは確率分布だけではうまく説明できない
  * 現実のデータに含まれるばらつきの例示
    * たくさんの植物個体の種子数を調べる
      * ある説明変数によって種子数が異なる
      * その説明変数が、全個体で同じだとすると→$\lambda$が同じ値になるから、どの個体の種子数も同じ分布に従うはず
      * でも、現実にはそうはならないよね、という話
    * 個体差
      * 観測できない個体差というものが必ずある
      * 観測できないけど、「観測しない個体差」としてモデルに組み込むことはできる
        * いままでのGLMには、そういう項はなかった
    * 一般化線形混合モデル（generalized linea mixed model; GLMM）
      * データのばらつきを二項分布とかポアソン分布で
      * 個体差を正規分布で
      * 部品として使う確率分布が複数になる
    * ちなみに
      * これ以降に出てくる場所差・個体差は説明変数にはなり得ないもののことなので注意＝制御できないし観測できない
      
## 7.1 例題：GLMでは説明できないカウントデータ
  * 基本情報
    * 植物の各個体から8個の種子、そのうち生きてる数＝有限個数の2値データ＝二項分布
    * 葉っぱの数によって生存数がどう変わるか
    * 個体$i$の種子が8個全部生きてたら$y_i=8$, 全部死んでたら$y_i=0$
    * 葉数$x_i$、$x_i$の範囲が2--6で100個体集める
  * GLMなら...
    * 114ページの表で二項分布のリンク関数を確認する→ロジット関数
    * $logit(q_i)=\beta_1+\beta_2x_i$ ロジット関数のパラメータ$q_i$(2値のうち1方となる確率)は
    * やってみる
    
```{r}
dat<-read.csv('./kubobook_2012-2/glmm/data.csv')
glm(cbind(y, N-y) ~ x, data=dat, family=binomial)
```
    
  